default: &default
  todo_notifications_worker:
    cron: "0 * * * *"
    class: "TodoNotificationsWorker"
    queue: "default"

development:
  todo_notifications_worker:
    cron: "* * * * *"
    queue: "default"

test:
    class: "TodoNotificationsWorker"
  <<: *default

staging:
  <<: *default

production:
  <<: *default